Add support of mount point feature for HashiCorp Vault provider
nautobot/nautobot-plugin-secrets-providers pull request #25
Opened 2022-03-23 10:17 UTC by FloLaco

I'm adding the possibility to specify the mounting point for Hashicorp Vault.
More info about mounting vault : https://learn.hashicorp.com/tutorials/vault/namespace-structure?in=vault/enterprise#understand-vault-s-mount-points

Why supporting mount point ?
If we enable a new KV engine, it will create another mounting point which is not accessible on "secret/" mounting point.
![image](https://user-images.githubusercontent.com/1486562/159676399-fe8c7f86-8e7f-4a5e-bdd3-7c3dcc3cba5a.png)

2022-03-29 17:36 UTC, jathanism commented
Thanks for this contribution. I'll get this pulled in for review!

2022-04-05 21:40 UTC, jathanism requested changes
This is looking great! Just a couple minor changes requested for style! Thank you.

2022-04-05 21:40 UTC, jathanism commented on nautobot_secrets_providers/providers/hashicorp.py
> +            help_text=f"The path where the secret engine was mounted on (default value: {DEFAULT_MOUNT_POINT})",
```suggestion
            help_text=f"The path where the secret engine was mounted on (Default: <code>{DEFAULT_MOUNT_POINT}</code>)",
```

2022-04-05 21:40 UTC, jathanism commented on nautobot_secrets_providers/providers/hashicorp.py
> +                secret_mount_point = DEFAULT_MOUNT_POINT
```suggestion
            secret_mount_point = parameters.get("mount_point", DEFAULT_MOUNT_POINT)
```

2022-04-05 21:40 UTC, jathanism commented on nautobot_secrets_providers/tests/test_providers.py
> +        """Retrieve a secret successfully."""
```suggestion
        """Retrieve a secret successfully using a custom `mount_point`."""
```

2022-04-08 00:05 UTC, jathanism approved these changes

2022-04-08 13:59 UTC, merged

2022-04-10 07:45 UTC, FloLaco commented
@jathanism thanks for applying these changes.